x-airflow-common: &airflow-common
  image: apache/airflow:2.11.0
  env_file:
    - .env

  environment:
    AIRFLOW__CORE__EXECUTOR: ${AIRFLOW__CORE__EXECUTOR}
    AIRFLOW__CORE__LOAD_EXAMPLES: ${AIRFLOW__CORE__LOAD_EXAMPLES}
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
    AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}


  user: "${AIRFLOW_UID}:0"

  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./airflow/config:/opt/airflow/config

  depends_on:
    postgres:
      condition: service_healthy


services:

  ####################################################
  # PostgreSQL
  ####################################################

  postgres:
    image: postgres:17
    container_name: data-platform-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  ####################################################
  # pgAdmin
  ####################################################

  pgadmin:
    image: dpage/pgadmin4
    container_name: data-platform-pgadmin
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

    ports:
      - "5050:80"

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    depends_on:
      postgres:
        condition: service_healthy


  ####################################################
  # Python
  ####################################################

  python-app:
    build:
      context: .
      dockerfile: docker/Dockerfile

    container_name: data-platform-python

    depends_on:
      postgres:
        condition: service_healthy


  ####################################################
  # Airflow
  ####################################################

  airflow-init:
    <<: *airflow-common

    container_name: data-platform-airflow-init

    restart: "no"

    entrypoint: /bin/bash

    command:
      - -c
      - |
        airflow db init && \
        airflow users create \
          --username ${AIRFLOW_USERNAME} \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email ${AIRFLOW_EMAIL} \
          --password ${AIRFLOW_PASSWORD}


  airflow-scheduler:
    <<: *airflow-common

    container_name: data-platform-airflow-scheduler

    restart: unless-stopped

    command: scheduler

    depends_on:
      postgres:
        condition: service_healthy

      airflow-init:
        condition: service_completed_successfully


  airflow-webserver:
    <<: *airflow-common

    container_name: data-platform-airflow-webserver

    restart: unless-stopped

    command: webserver

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy

      airflow-init:
        condition: service_completed_successfully
    
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5


volumes:
  postgres_data:
  pgadmin_data: