services:
  postgres:
    image: postgres:17
    container_name: data-platform-postgres

    environment:
      POSTGRES_USER: data_engineer
      POSTGRES_PASSWORD: data123
      POSTGRES_DB: data_platform

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: